## GPU 확인

In [1]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()  #gpu가 사용 가능한지 확인

True

In [3]:
torch.cuda.get_device_name(0)   #어떤 gpu를 사용하고 있는지 확인

'GeForce GTX 1650 with Max-Q Design'

In [4]:
torch.cuda.device_count()     #몇 개의 GPU를 사용할 수 있는지 확인

1

## Pytorch Tensor

In [5]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [6]:
print(t.dim())  # 차원(rank) 확인
print(t.size()) # shape 확인
print(t[:,1]) # 행(모두), 열(1열만)
print(t[:,:-1]) #행(모두), 열(맨 마지막 것만 제외)

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

###  자동으로 계산되기 때문에 주의!

In [7]:
# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [8]:
print('--------------')
print(' Mul vs MatMul')
print('--------------')

# Tensor 생성
a1 = torch.FloatTensor([[1,2],[3,4]])      # 2x2
a2 = torch.FloatTensor([[1],[2]])          # 2x1

print('Shape of Matrix a1 : ', a1.shape)
print('Shape of Matrix a2 : ', a2.shape)
print()
print('Result of MatMul(행렬 곱) : ') 
print(a1.matmul(a2))  # 행렬 곱 연산 결과
print()
print('Result of Mul(Element wise 곱셈) : ')
print(a1 * a2)        # 원소별 곱셈 연산 결과

--------------
 Mul vs MatMul
--------------
Shape of Matrix a1 :  torch.Size([2, 2])
Shape of Matrix a2 :  torch.Size([2, 1])

Result of MatMul(행렬 곱) : 
tensor([[ 5.],
        [11.]])

Result of Mul(Element wise 곱셈) : 
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [9]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [10]:
t1 = torch.LongTensor([1,2])  

try:                                #long type에서는 mean 연산이 안된다.(예외 처리)
    print(t1.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [11]:
t2 = torch.FloatTensor([[1,2],[3,4]])
print(t2)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(t2.mean())        # 모든 원소 평균
print(t2.mean(dim=0))   # 행끼리 평균
print(t2.mean(dim=1))   # 열끼리 평균
print(t2.mean(dim=-1))  # 마지막 차원(열)끼리 평균

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [13]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(t.sum())         # 모든 원소 합
print(t.sum(dim=0))    # 행끼리 합
print(t.sum(dim=1))    # 열끼리 합
print(t.sum(dim=-1))   # 마지막 차원(열)끼리 합

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

**Max - 2개의 값을 반환 (첫번째 : 가장 큰 원소의 값, 두번째 : Argmax)**

**Argmax - 가장 큰 원소가 위치해 있는 Index 값**

In [15]:
a = torch.FloatTensor([[1,2],[3,4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
print(a.max())       # tensor 원소 중 가장 큰 원소 값 찾기
print()
print(a.max(dim=0))  # 행을 기준으로 봤을 때 가장 큰 원소 값 찾기
print()
print(a.max(dim=1))  # 열을 기준으로 봤을 때 가장 큰 원소 값 찾기
print()
print(a.max(dim=-1)) # 마지막 차원(열)을 기준으로 봤을 때 가장 큰 원소 값 찾기


tensor(4.)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [17]:
print(a.max(dim=0))
print('Max : ',a.max(dim=0)[0])
print('ArgMax : ',a.max(dim=0)[1])


torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max :  tensor([3., 4.])
ArgMax :  tensor([1, 1])


## View

**텐서의 모양을 바꾸고 싶을 때 사용하는 함수**

**'-1'은 가장 변동이 심한 곳으로 넣어준다. (Ex. BatchSize)**

In [18]:
t = np.array([[[0,1,2],
               [3,4,5],
               [6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)     # numpy를 tensor로 변경
print(ft.shape)

torch.Size([1, 4, 3])


In [19]:
print(ft.view([-1,3]))        # -1은 알아서 바꿔주는 것, 2차원으로 만들고 마지막 index를 3으로 모양 바꾸기
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [20]:
print(ft.view([-1,1,3]))     # -1은 알아서 바꿔주는 것, 3차원으로 만들고 마지막 index를 3으로 모양 바꾸기
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

**Dimension의 element의 갯수가 1일 때, 1을 없에주는 역할**

In [21]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [22]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [23]:
print(ft.squeeze(dim=0))            # 차원을 정해주면 그 차원이 1일 경우만 제거가 된다.
print(ft.squeeze(dim=0).shape)
print()
print(ft.squeeze(dim=1))            # 차원을 정해주면 그 차원이 1일 경우만 제거가 된다.
print(ft.squeeze(dim=1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

**원하는 dimension에 1을 추가하여 준다**

In [24]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [25]:
print(ft.unsqueeze(0))          # dim = 0인 곳에 차원을 1 추가
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [26]:
print(ft.view(1,-1))          # dim = 0인 곳에 차원을 1 추가, 뒤에는 알아서 맞춰주기
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [27]:
print(ft.unsqueeze(1))         # dim = 1인 곳에 차원을 1 추가
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
print(ft.view(-1,1))          # dim = 1인 곳에 차원을 1 추가, 뒤에는 알아서 맞춰주기
print(ft.view(-1, 1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
print(ft.unsqueeze(-1))         # dim이 마지막인 곳에 차원을 1 추가
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Scatter

**주로 one hot encoding을 진행할 때 쓰이는 함수**

**세가지 인자 - (dim)차원, (Index)정답 값의 위치, (src)어떤 Value로 표현할 것인지**

In [30]:
It = torch.LongTensor([[0],[1],[2],[0]])
print(It)

tensor([[0],
        [1],
        [2],
        [0]])


In [31]:
one_hot = torch.zeros(4,3)     # batch_size = 4, classes = 3
one_hot.scatter_(1,It,2)       
print(one_hot)

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.],
        [2., 0., 0.]])


## Concatenation

**Tensor들을 합치는 함수**

**차원을 명시해주면 그 차원을 축으로 Tensor들이 합쳐진다.**

In [32]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [33]:
print(torch.cat([x,y], dim = 0)) # 0번째 차원을 기준으로 합치기
print(torch.cat([x,y], dim = 1)) # 1번째 차원을 기준으로 합치기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

**Concatenate를 편리하게 해주는 함수(그냥 Tensor를 쌓는 함수로 생각하자)**


In [34]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [35]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))     # 차원을 명시해주면 그 방향으로 쌓는다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [36]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0))
#stack과 동일한 결과

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## In-place Operation (덮어쓰기 연산)

In [37]:
x = torch.FloatTensor([[1,2],[3,4]])

In [38]:
print(x.mul(2.))     # 2를 곱한 값을 수행
print(x)             # 기존의 값을 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(x.mul_(2.))     # 2를 곱한 값을 수행
print(x)              # 기존의 값을 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
