## XOR with Linear Layer

## Import Required Libraries

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
# for reproducibility
torch.manual_seed(815)
if device == 'cuda':
    torch.cuda.manual_seed_all(815)

cuda


### Data 

In [3]:
# GPU로 Train을 돌릴 것이기 때문에 .to(device)를 붙여준다.

X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)  
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

### Linear Layer

In [4]:
linear = nn.Linear(2,1,bias = True)  # Input : 2, Output : 1
sigmoid = nn.Sigmoid()

In [5]:
# Model
model = nn.Sequential(linear, sigmoid).to(device)

# Loss function
criterion = nn.BCELoss().to(device)

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=5)

### Train

In [6]:
for step in range(10001):
    # 결과 예측 
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    
   
    optimizer.zero_grad()    # 기울기 값 초기화
    cost.backward()          # 기울기 값 Update
    optimizer.step()         # 기울기 값으로 Weight값 Update

    if step % 1000 == 0:
        print(step, cost.item())

0 0.7062350511550903
1000 0.6931471824645996
2000 0.6931471824645996
3000 0.6931471824645996
4000 0.6931471824645996
5000 0.6931471824645996
6000 0.6931471824645996
7000 0.6931471824645996
8000 0.6931471824645996
9000 0.6931471824645996
10000 0.6931471824645996


In [7]:
# Accuracy computation
# True if hypothesis>0.5 else False

with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('Hypothesis: \n', hypothesis.detach().cpu().numpy())    # hypothesis.cpu().numpy()랑 같다!
    print('Correct: \n', predicted.detach().cpu().numpy())
    print('Accuracy: \n', accuracy.item())
    
# Tensor를 Numpy로 변경해주려면 cpu()로 변경을 해주고 변환을 진행해야 한다.

Hypothesis: 
 [[0.49999714]
 [0.49999547]
 [0.49999547]
 [0.4999938 ]]
Correct: 
 [[0.]
 [0.]
 [0.]
 [0.]]
Accuracy: 
 0.5


### 아무리 학습을 시켜도 정확도가 0.5가 나온다! 
### >> Layer를 늘려서 Train을 해보자.

#### Linear Layer를 2개로 늘린 것 이외에는 모든 것이 동일!

### Data

In [8]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)  
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

### Multi Linear Layer

In [9]:
# nn layers
linear1 = nn.Linear(2, 2, bias=True)
linear2 = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()

In [10]:
# Model
model = nn.Sequential(linear1, sigmoid, linear2, sigmoid).to(device)

# Loss function
criterion = nn.BCELoss().to(device)

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=5)

In [11]:
for step in range(10001):
    
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, cost.item())

0 0.695436954498291
1000 0.0024990083184093237
2000 0.0010658728424459696
3000 0.0006756555521860719
4000 0.0004940968938171864
5000 0.0003892949316650629
6000 0.0003210976137779653
7000 0.0002731611020863056
8000 0.00023767226957716048
9000 0.0002103075385093689
10000 0.00018859218107536435


In [12]:
# Accuracy computation
# True if hypothesis>0.5 else False

with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('Hypothesis: \n', hypothesis.detach().cpu().numpy())    # hypothesis.cpu().numpy()랑 같다!
    print('Correct: \n', predicted.detach().cpu().numpy())
    print('Accuracy: \n', accuracy.item())
    
# Tensor를 Numpy로 변경해주려면 cpu()로 변경을 해주고 변환을 진행해야 한다.

Hypothesis: 
 [[1.6553845e-04]
 [9.9979180e-01]
 [9.9979180e-01]
 [1.7230240e-04]]
Correct: 
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy: 
 1.0


### Model에 더 많은 Layer를 늘려서 Train을 해보자!

In [13]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

#### Layer 4개로 Model을 만들자.

In [14]:
# nn layers
linear1 = nn.Linear(2, 10, bias=True)
linear2 = nn.Linear(10, 10, bias=True)
linear3 = nn.Linear(10, 10, bias=True)
linear4 = nn.Linear(10, 1, bias=True)
sigmoid = nn.Sigmoid()

In [18]:
# model
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid, linear3, sigmoid, linear4, sigmoid).to(device)

# Loss function
criterion = nn.BCELoss().to(device)

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=1)   # learning rate를 조절해보며 Train해보자

In [19]:
for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)

    # cost/loss function
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, cost.item())

0 3.4809963835868984e-05
1000 3.402016227482818e-05
2000 3.327506783534773e-05
3000 3.252997703384608e-05
4000 3.182958971592598e-05
5000 3.1159008358372375e-05
6000 3.0533134122379124e-05
7000 2.992216104757972e-05
8000 2.9340990295168012e-05
9000 2.8759821361745708e-05
10000 2.8208458388689905e-05


In [20]:
# Accuracy computation
# True if hypothesis>0.5 else False

with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print('Hypothesis: \n', hypothesis.detach().cpu().numpy())    # hypothesis.cpu().numpy()랑 같다!
    print('Correct: \n', predicted.detach().cpu().numpy())
    print('Accuracy: \n', accuracy.item())
    
# Tensor를 Numpy로 변경해주려면 cpu()로 변경을 해주고 변환을 진행해야 한다.

Hypothesis: 
 [[6.4789215e-06]
 [9.9995506e-01]
 [9.9995315e-01]
 [1.4523312e-05]]
Correct: 
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy: 
 1.0
