## Neural Network with 2D data

- Neural Network with 4 layers
- 2D data $f(x,y)$ -> R

### 1. Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable

### 2. Data Generation

In [2]:
num_data = 100
num_epoch = 1000

x = init.uniform_(torch.Tensor(num_data,1),-10,-10)
y = init.uniform_(torch.Tensor(num_data,1),-10,-10)
z = x**2 + y**2

x_noise = x + init.normal_(torch.FloatTensor(num_data,1),std = 1)
y_noise = y + init.normal_(torch.FloatTensor(num_data,1),std = 1)
z_noise = x_noise**2 + y_noise**2

data_noise = torch.cat([x,y,z_noise],1)


### 3. Model & Optimizer

In [3]:
model = nn.Sequential(
        nn.Linear(2,20),
        nn.ReLU(),
        nn.Linear(20,10),
        nn.ReLU(),
        nn.Linear(10,5),
        nn.ReLU(),
        nn.Linear(5,5),
        nn.ReLU(),
        nn.Linear(5,1),
        ).cuda()  #gpu로 동작하게 하기 위해서

loss_func = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

### 4. Train

In [5]:
input_data = torch.cat([x,y],1).cuda()
label = z_noise.cuda()
loss_arr = []

for i in range(num_epoch):
    optimizer.zero_grad()  #기울기 초기화해야 업데이트가 제대로 됨
    output = model(Variable(input_data))
    loss = loss_func(output,Variable(label))
    loss.backward()
    optimizer.step()
    
    loss_arr.append(loss.cpu().data.numpy())
    
    if i % 100 == 0:
        print(loss.data.item())
        data = torch.cat([input_data.cpu(), output.cpu().data],1)
        

205.43310546875
190.18377685546875
25.239051818847656
22.511249542236328
22.511211395263672
22.511211395263672
22.511211395263672
22.511337280273438
22.511640548706055
22.511211395263672


### 5. Check Trained Parameters

In [8]:
param_list = list(model.parameters()) #모델 안에 있는 파라미터들 확인
print(param_list[0].data)
print(param_list[1].data)
print(param_list[2].data)

tensor([[-1.0225, -0.9568],
        [-0.2232, -0.4610],
        [-0.0011,  0.0833],
        [ 0.4745,  0.4172],
        [-0.7816, -0.7500],
        [ 0.6048,  0.0687],
        [ 0.0113,  0.4504],
        [-0.1926, -0.4556],
        [ 0.6268,  0.1193],
        [ 0.5768,  0.3336],
        [ 0.5596,  0.6201],
        [-0.8184, -0.3752],
        [-0.9314, -0.2216],
        [-0.8435, -0.9622],
        [-1.0188, -0.8250],
        [ 0.5844, -0.2008],
        [ 0.2642,  0.4341],
        [-0.0754, -0.9046],
        [ 0.5627,  0.1488],
        [ 0.2512, -0.1937]], device='cuda:0')
tensor([-0.3258,  0.4018,  0.0996, -0.6793, -0.1895,  0.3144,  0.5303,  0.0058,
        -0.1403,  0.3683, -0.5705,  0.6863, -0.1210,  0.2316,  0.8596,  0.1294,
        -0.2880, -0.1808, -0.4007, -0.6178], device='cuda:0')
tensor([[-6.3820e-02,  7.8657e-02,  2.0878e-01, -2.0813e-01, -1.4042e-01,
          4.5164e-02, -1.8210e-01,  1.6079e-01,  9.5009e-02,  4.9711e-03,
         -2.2169e-01,  3.2291e-02,  2.0991e-02,  1.6