## GPU 확인

In [1]:
import torch

torch.cuda.is_available()  #gpu가 사용 가능한지 확인

True

In [2]:
torch.cuda.get_device_name(0)   #어떤 gpu를 사용하고 있는지 확인

'GeForce GTX 1650 with Max-Q Design'

In [3]:
torch.cuda.device_count()     #몇 개의 GPU를 사용할 수 있는지 확인

1

## Variable & Automatic Gradient Calculation

- Tensor vs Variable
- Graph and Gradient

### 1. Import Required Libraries

In [4]:
import torch
from torch.autograd import Variable

### 2. Tensor vs Variable

1) Declaration

In [5]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
x_variable = Variable(x_tensor)
x_variable

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

2) Variables of a Variable

Variable class가 tensor를 감싸고 있다고 생각하자. 

Variable.data 하면 안에 들어있는 tensor를 볼 수 있다. 

Variable은 gradient를 계산할 수 있다!  

torch version이 upgrade 되면서 최근 버전은 tensor만 써도 gradient가 계산 가능하다.  

In [7]:
# .data -> wrapped tensor
x_variable.data

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
# .grad -> gradient of the variable 계산을 아무것도 안했기 때문에..
print(x_variable.grad)

None


In [9]:
# .requires_grad -> whether variable requres gradient 처음에 gradient 계산을 설정할 수 있다.
print(x_variable.requires_grad)

x_variable = Variable(x_tensor,requires_grad=True)
x_variable.requires_grad

False


True

In [10]:
# .volatile -> inference mode with minimal memory usage  -> 이거 이제 안씀...
# 모델을 학습하고 inference 할 때 사용 불필요한 연산을 제거하는 용도
# single volatile variable makes whole graph not requiring gradient

x_variable = Variable(x_tensor,requires_grad=True)

with torch.no_grad():            ##이것의 유무에 따라서 gradient를 계산할지 안할지가 결정된다.  앞으로 feed forward만 하도록 하게된다.
    x_variable = Variable(x_tensor)

x_variable.grad, x_variable.requires_grad


(None, False)

### 3. Graph & Variables 

In [11]:
#create graph

x = Variable(torch.FloatTensor(3,4),requires_grad = True)
y = x**2 + 4*x
z = 2* y + 3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [12]:
# .backward(gradient, retain_graph, create_graph, retain_variables)
# compute gradient of current variable w.r.t graph leaves

loss = torch.FloatTensor(3,4)
z.backward(loss)

print(x.grad) 
y.grad, z.grad
#위 식이 x에 대해서 이루어져 있는 식이기 때문에 
# leaf node의 기울기만 계산이 가능하다.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


(None, None)